
=================================== ERRORS ====================================
___________ ERROR collecting tests/unit_tests/test_auth_service.py ____________
ImportError while importing test module 'C:\Users\Behgozin\Desktop\Shakour\Projects\GravityManagement\backend\tests\unit_tests\test_auth_service.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
backend\tests\unit_tests\test_auth_service.py:5: in <module>
    from jose import jwt, JWTError
E   ModuleNotFoundError: No module named 'jose'
=========================== short test summary info ===========================
ERROR backend\tests\unit_tests\test_auth_service.py
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
4 warnings, 1 error in 34.24s

